---
- name: install nginx
  package:
    name: nginx
    state: present

- name: copy WordPress nginx configuration
  template:
    src: wordpress.conf
    dest: /etc/nginx/conf.d/wordpress.conf
  notify: restart nginx

- name: insert firewalld rule for nginx
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: yes
  ignore_errors: yes

- name: start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
