---
- name: install build dependencies
  package:
    state: present
    name:
      - gcc-c++
      - libicu-devel

  # Ignore errors because `yarn` sometimes produces non-fatal exit codes that
  # Ansible interprets as a fatal exit code
- name: install runtime dependencies with yarn
  become: yes
  become_user: teleirc
  command: "yarn"
  args:
    chdir: "/usr/lib64/teleirc/{{ item.value.cn }}/"
  loop: "{{ bots|dict2items }}"
  ignore_errors: yes

- name: remove build dependencies
  package:
    state: absent
    name:
      - gcc-c++
      - libicu-devel

- name: restart teleirc
  service:
    name: "teleirc-{{ item.value.cn }}.service"
    state: restarted
  loop: "{{ bots|dict2items }}"
