---
- name: restart teleirc
  service:
    name: "teleirc-{{ item.value.cn }}.service"
    state: restarted
  loop: "{{ bots|dict2items }}"

- name: systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
