os: linux
jobs:
  include:
    - language: python
      python: 3.8
      install:
        - pip install pipenv
        - pipenv install --dev
      script: "yamllint -c .yamllint ."

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#rit-foss-admin"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always
