---
- name: install/upgrade EPEL repositories
  package:
    state: latest
    name: epel-release

- name: install base packages
  package:
    state: present
    name:
      - certbot
      - duply
      - git
      - htop
      - python36
      - python36-pip

- name: enable SELinux
  selinux:
    policy: targeted
    state: enforcing
