---
- name: install dependencies and SELinux tools
  package:
    state: present
    name:
      - MySQL-python
      - libselinux-python
      - policycoreutils-python

- name: create web server directory
  file:
    state: directory
    path: /var/www

- name: download and extract archive
  unarchive:
    creates: /var/www/wordpress/
    dest: /var/www/
    remote_src: yes
    src: https://wordpress.org/latest.tar.gz

- name: add group "wordpress"
  group:
    name: wordpress

- name: add user "wordpress"
  user:
    name: wordpress
    group: wordpress
    home: /var/www/wordpress/

- name: register random salts for WordPress config
  register: wp_salt
  uri:
    return_content: yes
    url: https://api.wordpress.org/secret-key/1.1/salt/

- name: create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: copy WordPress config file
  template:
    src: wp-config.php
    dest: /var/www/wordpress/

- name: change ownership of WordPress installation
  file:
    path: /var/www/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: yes

- name: set SELinux policy for Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/var/www/wordpress(/.*)?"

- name: set SELinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/var/www/wordpress/wp-config\.php"

- name: set SELinux policy for wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/wordpress/wp-content(/.*)?"

- name: set SELinux policy for PHP files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/var/www/wordpress/.*\.php"

- name: set SELinux policy for upgrade/ directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/wordpress/wp-content/upgrade(/.*)?"

- name: set SELinux policy for uploads/ directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/wordpress/wp-content/uploads(/.*)?"

- name: set SELinux policy for wp-includes PHP files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/var/www/wordpress/wp-includes/.*\.php"

- name: set SELinux on all files
  command: restorecon -Rv /var/www/wordpress

- name: start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes
