---
# This playbook will install MariaDB and create db user and give permissions.

- name: remove older versions of conflicting packages
  package:
    state: absent
    name:
      - mariadb-libs

- name: install MariaDB
  package:
    state: present
    name:
      - mariadb101u-server

- name: copy MySQL configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mariadb

- name: create MariaDB log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0644

- name: start and enable MariaDB service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: add MariaDB firewalld rule
  firewalld:
    service: mysql
    state: enabled
    immediate: yes
    permanent: true
