---
- name: install EPEL repository
  package:
    name: epel-release
    state: present

- name: install IUS repository
  package:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present
  
- name: install firewalld
  package:
    name: firewalld
    state: present

- name: start and enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes
