---
- name: create system user for TeleIRC bots
  user:
    name: teleirc
    comment: "system user for RITlug/teleirc bots - do not use interactively"
    system: yes
    home: /etc/teleirc
    create_home: no

- name: add target user to TeleIRC admin group
  user:
    name: "{{ item }}"
    groups: teleirc
    append: yes
  loop: "{{ authorized_users }}"

- name: create root directory for TeleIRC bots
  file:
    state: directory
    path: "/etc/teleirc"
    mode: 0755
    setype: etc_t
    seuser: system_u
