---
- name: create system user for TeleIRC bots
  user:
    name: teleirc
    comment: "system user to run RITlug/teleirc bots - do not use"
    system: yes
    home: "/usr/lib64/teleirc"
    create_home: no

- name: add target user to TeleIRC admin group
  user:
    name: "{{ target_user }}"
    groups: teleirc
    append: yes

- name: create root directory for TeleIRC bots
  file:
    state: directory
    path: "/usr/lib64/teleirc"
    mode: 0755
    owner: teleirc
    group: teleirc
    seuser: system_u
