---
- name: ensure authorized users exist
  user:
    name: "{{ item.key }}"
  loop: "{{ authorized_users|dict2items }}"

- name: create SSH config directories for authorized users (~/.ssh)
  file:
    state: directory
    path: "{{ item.value.home_dir }}/.ssh"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0700
  loop: "{{ authorized_users|dict2items }}"

- name: add SSH public keys for authorized users (~/.ssh/authorized_keys)
  template: 
    src: authorized_keys
    dest: "{{ item.value.home_dir }}/.ssh/authorized_keys"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    mode: 0400
  loop: "{{ authorized_users|dict2items }}"

- name: configure SSH server (/etc/ssh/sshd_config)
  template: 
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
  notify: restart sshd
