---
- name: ensure authorized users exist
  user:
    name: "{{ item }}"
  loop: "{{ users }}"

- name: create SSH config directories for authorized users (~/.ssh)
  file:
    state: directory
    path: "/home/{{ item }}/.ssh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  loop: "{{ users }}"

- name: add SSH public key to authorized_keys for target user (~/.ssh/authorized_keys)
  template: 
    src: "authorized_keys.{{ item }}"
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0400
  loop: "{{ users }}"

- name: configure SSH server (/etc/ssh/sshd_config)
  template: 
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
  notify: restart sshd
